import { addDays } from "./dates";
import { DEMO_TODAY } from "./types";
import type {
  AppState,
  AvailabilityWindow,
  FloorTask,
  Integration,
  NewsItem,
  Person,
  Punch,
  Shift,
  ShiftOffer,
  Store,
  SyncEvent,
  TimeOffRequest,
} from "./types";

export const STORES: Store[] = [
  {
    id: "st-bondi",
    name: "Northside Fresh Bondi Junction",
    code: "NF-104",
    suburb: "Bondi Junction",
    state: "NSW",
    address: "1 Oxford St, Bondi Junction NSW 2022",
    timezone: "Australia/Sydney",
    format: "Supermarket",
    geofenceMeters: 120,
  },
  {
    id: "st-newtown",
    name: "Northside Fresh Newtown Metro",
    code: "NF-221",
    suburb: "Newtown",
    state: "NSW",
    address: "180 King St, Newtown NSW 2042",
    timezone: "Australia/Sydney",
    format: "Metro",
    geofenceMeters: 80,
  },
  {
    id: "st-parra",
    name: "Northside Fresh Parramatta",
    code: "NF-318",
    suburb: "Parramatta",
    state: "NSW",
    address: "4 Church St, Parramatta NSW 2150",
    timezone: "Australia/Sydney",
    format: "Supermarket",
    geofenceMeters: 140,
  },
];

export const PEOPLE: Person[] = [
  {
    id: "p-alex",
    firstName: "Alex",
    lastName: "Chen",
    preferredName: "Alex",
    email: "alex.chen@northsidefresh.test",
    phone: "0412 880 104",
    roleId: "team_member",
    storeId: "st-bondi",
    departmentId: "checkout",
    secondaryDepartments: ["customer_service"],
    avatarHue: 152,
    contractedHours: 24,
    awardLevel: "GRIA L2",
    startDate: "2024-03-11",
    status: "active",
    employeeNumber: "104882",
  },
  {
    id: "p-mei",
    firstName: "Mei",
    lastName: "Tran",
    preferredName: "Mei",
    email: "mei.tran@northsidefresh.test",
    phone: "0418 220 551",
    roleId: "team_member",
    storeId: "st-bondi",
    departmentId: "checkout",
    secondaryDepartments: [],
    avatarHue: 28,
    contractedHours: 20,
    awardLevel: "GRIA L1",
    startDate: "2025-11-02",
    status: "active",
    employeeNumber: "110204",
  },
  {
    id: "p-luca",
    firstName: "Luca",
    lastName: "Rossi",
    preferredName: "Luca",
    email: "luca.rossi@northsidefresh.test",
    phone: "0421 667 019",
    roleId: "team_member",
    storeId: "st-bondi",
    departmentId: "fresh",
    secondaryDepartments: ["grocery"],
    avatarHue: 198,
    contractedHours: 32,
    awardLevel: "GRIA L3",
    startDate: "2022-08-08",
    status: "active",
    employeeNumber: "098441",
  },
  {
    id: "p-harper",
    firstName: "Harper",
    lastName: "Singh",
    preferredName: "Harper",
    email: "harper.singh@northsidefresh.test",
    phone: "0403 991 228",
    roleId: "team_member",
    storeId: "st-bondi",
    departmentId: "nightfill",
    secondaryDepartments: ["grocery"],
    avatarHue: 262,
    contractedHours: 28,
    awardLevel: "GRIA L2",
    startDate: "2023-06-19",
    status: "active",
    employeeNumber: "101773",
  },
  {
    id: "p-noah",
    firstName: "Noah",
    lastName: "Williams",
    preferredName: "Noah",
    email: "noah.williams@northsidefresh.test",
    phone: "0433 118 640",
    roleId: "team_member",
    storeId: "st-bondi",
    departmentId: "online",
    secondaryDepartments: ["checkout"],
    avatarHue: 210,
    contractedHours: 20,
    awardLevel: "GRIA L2",
    startDate: "2024-09-30",
    status: "active",
    employeeNumber: "107220",
  },
  {
    id: "p-elise",
    firstName: "Elise",
    lastName: "Moreau",
    preferredName: "Elise",
    email: "elise.moreau@northsidefresh.test",
    phone: "0455 772 013",
    roleId: "team_member",
    storeId: "st-bondi",
    departmentId: "bakery",
    secondaryDepartments: ["deli"],
    avatarHue: 12,
    contractedHours: 30,
    awardLevel: "GRIA L3",
    startDate: "2021-02-14",
    status: "active",
    employeeNumber: "088102",
  },
  {
    id: "p-jordan",
    firstName: "Jordan",
    lastName: "Blake",
    preferredName: "Jordan",
    email: "jordan.blake@northsidefresh.test",
    phone: "0417 550 882",
    roleId: "team_lead",
    storeId: "st-bondi",
    departmentId: "fresh",
    secondaryDepartments: ["deli"],
    avatarHue: 88,
    contractedHours: 38,
    awardLevel: "GRIA L4",
    startDate: "2019-04-01",
    status: "active",
    employeeNumber: "074419",
  },
  {
    id: "p-casey",
    firstName: "Casey",
    lastName: "Nguyen",
    preferredName: "Casey",
    email: "casey.nguyen@northsidefresh.test",
    phone: "0429 331 074",
    roleId: "department_manager",
    storeId: "st-bondi",
    departmentId: "checkout",
    secondaryDepartments: ["customer_service", "online"],
    avatarHue: 330,
    contractedHours: 38,
    awardLevel: "GRIA L5",
    startDate: "2018-11-12",
    status: "active",
    employeeNumber: "070881",
  },
  {
    id: "p-priya",
    firstName: "Priya",
    lastName: "Nair",
    preferredName: "Priya",
    email: "priya.nair@northsidefresh.test",
    phone: "0408 226 910",
    roleId: "store_manager",
    storeId: "st-bondi",
    departmentId: "customer_service",
    secondaryDepartments: [],
    avatarHue: 168,
    contractedHours: 38,
    awardLevel: "Salaried",
    startDate: "2016-07-04",
    status: "active",
    employeeNumber: "055102",
  },
  {
    id: "p-sam",
    firstName: "Sam",
    lastName: "Okonkwo",
    preferredName: "Sam",
    email: "sam.okonkwo@northsidefresh.test",
    phone: "0411 900 333",
    roleId: "area_manager",
    storeId: "st-bondi",
    departmentId: "customer_service",
    secondaryDepartments: [],
    avatarHue: 42,
    contractedHours: 38,
    awardLevel: "Salaried",
    startDate: "2014-01-20",
    status: "active",
    employeeNumber: "041990",
  },
  {
    id: "p-morgan",
    firstName: "Morgan",
    lastName: "Lee",
    preferredName: "Morgan",
    email: "morgan.lee@northsidefresh.test",
    phone: "0432 774 118",
    roleId: "people_culture",
    storeId: "st-bondi",
    departmentId: "customer_service",
    secondaryDepartments: [],
    avatarHue: 300,
    contractedHours: 38,
    awardLevel: "Salaried",
    startDate: "2020-05-18",
    status: "active",
    employeeNumber: "082441",
  },
  {
    id: "p-dana",
    firstName: "Dana",
    lastName: "Whitfield",
    preferredName: "Dana",
    email: "dana.whitfield@northsidefresh.test",
    phone: "0477 210 664",
    roleId: "payroll",
    storeId: "st-bondi",
    departmentId: "customer_service",
    secondaryDepartments: [],
    avatarHue: 220,
    contractedHours: 38,
    awardLevel: "Salaried",
    startDate: "2017-09-11",
    status: "active",
    employeeNumber: "061228",
  },
  {
    id: "p-riley",
    firstName: "Riley",
    lastName: "Park",
    preferredName: "Riley",
    email: "riley.park@northsidefresh.test",
    phone: "0490 118 225",
    roleId: "admin",
    storeId: "st-bondi",
    departmentId: "customer_service",
    secondaryDepartments: [],
    avatarHue: 190,
    contractedHours: 38,
    awardLevel: "Salaried",
    startDate: "2015-03-02",
    status: "active",
    employeeNumber: "048003",
  },
  {
    id: "p-tom",
    firstName: "Tom",
    lastName: "Hale",
    preferredName: "Tom",
    email: "tom.hale@northsidefresh.test",
    phone: "0466 331 909",
    roleId: "team_member",
    storeId: "st-newtown",
    departmentId: "checkout",
    secondaryDepartments: ["grocery"],
    avatarHue: 48,
    contractedHours: 16,
    awardLevel: "GRIA L1",
    startDate: "2026-01-13",
    status: "active",
    employeeNumber: "112008",
  },
  {
    id: "p-aisha",
    firstName: "Aisha",
    lastName: "Rahman",
    preferredName: "Aisha",
    email: "aisha.rahman@northsidefresh.test",
    phone: "0422 880 441",
    roleId: "store_manager",
    storeId: "st-newtown",
    departmentId: "customer_service",
    secondaryDepartments: [],
    avatarHue: 140,
    contractedHours: 38,
    awardLevel: "Salaried",
    startDate: "2019-10-07",
    status: "active",
    employeeNumber: "079554",
  },
];

function shift(
  id: string,
  personId: string | null,
  storeId: string,
  departmentId: Shift["departmentId"],
  date: string,
  start: string,
  end: string,
  roleLabel: string,
  extras: Partial<Shift> = {},
): Shift {
  return {
    id,
    personId,
    storeId,
    departmentId,
    date,
    start,
    end,
    breakMinutes: extras.breakMinutes ?? 30,
    roleLabel,
    status: extras.status ?? "published",
    published: extras.published ?? true,
    notes: extras.notes,
  };
}

const mon = addDays(DEMO_TODAY, -5);
const tue = addDays(DEMO_TODAY, -4);
const wed = addDays(DEMO_TODAY, -3);
const thu = addDays(DEMO_TODAY, -2);
const fri = addDays(DEMO_TODAY, -1);
const sat = DEMO_TODAY;
const sun = addDays(DEMO_TODAY, 1);
const nextMon = addDays(DEMO_TODAY, 2);
const nextTue = addDays(DEMO_TODAY, 3);
const nextWed = addDays(DEMO_TODAY, 4);

export const SHIFTS: Shift[] = [
  shift("sh-alex-fri", "p-alex", "st-bondi", "checkout", fri, "12:00", "20:00", "Checkout"),
  shift("sh-alex-sat", "p-alex", "st-bondi", "checkout", sat, "09:00", "17:00", "Checkout"),
  shift("sh-alex-sun", "p-alex", "st-bondi", "checkout", sun, "10:00", "16:00", "Checkout"),
  shift("sh-alex-tue", "p-alex", "st-bondi", "checkout", nextTue, "14:00", "21:00", "Checkout"),
  shift("sh-mei-sat", "p-mei", "st-bondi", "checkout", sat, "07:00", "13:00", "Checkout", {
    breakMinutes: 15,
  }),
  shift("sh-mei-sun", "p-mei", "st-bondi", "checkout", sun, "08:00", "14:00", "Service desk"),
  shift("sh-mei-mon", "p-mei", "st-bondi", "checkout", nextMon, "09:00", "15:00", "Checkout"),
  shift("sh-luca-sat", "p-luca", "st-bondi", "fresh", sat, "06:00", "14:00", "Produce"),
  shift("sh-luca-sun", "p-luca", "st-bondi", "fresh", sun, "06:00", "12:00", "Produce", {
    breakMinutes: 15,
  }),
  shift("sh-luca-wed", "p-luca", "st-bondi", "fresh", nextWed, "05:30", "13:30", "Produce"),
  shift("sh-harper-fri", "p-harper", "st-bondi", "nightfill", fri, "21:00", "04:00", "Nightfill"),
  shift("sh-harper-sat", "p-harper", "st-bondi", "nightfill", sat, "21:00", "04:00", "Nightfill"),
  shift("sh-noah-sat", "p-noah", "st-bondi", "online", sat, "08:00", "16:00", "eStore pick"),
  shift("sh-noah-sun", "p-noah", "st-bondi", "online", sun, "08:00", "14:00", "eStore pick"),
  shift("sh-elise-sat", "p-elise", "st-bondi", "bakery", sat, "05:00", "13:00", "Bakery"),
  shift("sh-elise-sun", "p-elise", "st-bondi", "bakery", sun, "05:00", "11:00", "Bakery", {
    breakMinutes: 15,
  }),
  shift("sh-jordan-sat", "p-jordan", "st-bondi", "fresh", sat, "06:00", "15:00", "Fresh lead"),
  shift("sh-jordan-sun", "p-jordan", "st-bondi", "fresh", sun, "07:00", "15:00", "Fresh lead"),
  shift("sh-casey-sat", "p-casey", "st-bondi", "checkout", sat, "08:00", "17:00", "Front end"),
  shift("sh-priya-sat", "p-priya", "st-bondi", "customer_service", sat, "08:00", "17:00", "Store manager"),
  shift("sh-tom-sat", "p-tom", "st-newtown", "checkout", sat, "10:00", "18:00", "Checkout"),
  shift("sh-aisha-sat", "p-aisha", "st-newtown", "customer_service", sat, "08:00", "16:00", "Store manager"),
  shift("sh-open-sat-co", null, "st-bondi", "checkout", sat, "17:30", "21:30", "Checkout closer", {
    notes: "Late trade. Need a closer after the 5pm finish.",
    breakMinutes: 0,
  }),
  shift("sh-open-sun-on", null, "st-bondi", "online", sun, "14:00", "20:00", "eStore pick", {
    notes: "Click & collect surge after 3pm.",
  }),
  shift("sh-open-mon-nf", null, "st-bondi", "nightfill", nextMon, "21:00", "04:00", "Nightfill"),
  shift("sh-draft-wed", "p-alex", "st-bondi", "checkout", nextWed, "09:00", "17:00", "Checkout", {
    status: "draft",
    published: false,
  }),
  shift("sh-luca-give", "p-luca", "st-bondi", "fresh", nextTue, "06:00", "14:00", "Produce"),
  shift("sh-mei-swap-a", "p-mei", "st-bondi", "checkout", nextTue, "09:00", "15:00", "Checkout"),
  shift("sh-alex-swap-b", "p-alex", "st-bondi", "checkout", nextMon, "12:00", "20:00", "Checkout"),
  shift("sh-alex-mon", "p-alex", "st-bondi", "checkout", mon, "10:00", "18:00", "Checkout", {
    status: "completed",
  }),
  shift("sh-alex-wed", "p-alex", "st-bondi", "checkout", wed, "12:00", "20:00", "Checkout", {
    status: "completed",
  }),
  shift("sh-alex-thu", "p-alex", "st-bondi", "customer_service", thu, "09:00", "15:00", "Service desk", {
    status: "completed",
  }),
  shift("sh-mei-wed", "p-mei", "st-bondi", "checkout", wed, "08:00", "14:00", "Checkout", {
    status: "completed",
  }),
  shift("sh-luca-thu", "p-luca", "st-bondi", "fresh", thu, "06:00", "14:00", "Produce", {
    status: "completed",
  }),
];

export const OFFERS: ShiftOffer[] = [
  {
    id: "off-open-sat",
    kind: "open_claim",
    shiftId: "sh-open-sat-co",
    offeredById: "p-casey",
    status: "open",
    reason: "Late trade closer",
    createdAt: `${fri}T09:12:00.000Z`,
    eligibleDepartmentIds: ["checkout", "customer_service"],
  },
  {
    id: "off-open-sun",
    kind: "open_claim",
    shiftId: "sh-open-sun-on",
    offeredById: "p-priya",
    status: "open",
    reason: "eStore afternoon coverage",
    createdAt: `${fri}T11:40:00.000Z`,
    eligibleDepartmentIds: ["online", "checkout"],
  },
  {
    id: "off-open-mon",
    kind: "open_claim",
    shiftId: "sh-open-mon-nf",
    offeredById: "p-priya",
    status: "open",
    reason: "Nightfill call-in",
    createdAt: `${sat}T01:05:00.000Z`,
    eligibleDepartmentIds: ["nightfill", "grocery"],
  },
  {
    id: "off-luca-give",
    kind: "giveaway",
    shiftId: "sh-luca-give",
    offeredById: "p-luca",
    status: "open",
    reason: "Dentist, can't move it",
    createdAt: `${fri}T18:22:00.000Z`,
    eligibleDepartmentIds: ["fresh", "grocery"],
  },
  {
    id: "off-mei-swap",
    kind: "swap",
    shiftId: "sh-mei-swap-a",
    targetShiftId: "sh-alex-swap-b",
    offeredById: "p-mei",
    claimedById: "p-alex",
    status: "pending_approval",
    reason: "Uni tutorial moved to Tuesday morning",
    createdAt: `${thu}T20:14:00.000Z`,
    eligibleDepartmentIds: ["checkout"],
  },
];

export const PUNCHES: Punch[] = [
  {
    id: "pu-alex-mon-in",
    personId: "p-alex",
    shiftId: "sh-alex-mon",
    type: "in",
    at: `${mon}T00:02:00.000Z`,
    source: "app",
    insideGeofence: true,
  },
  {
    id: "pu-alex-mon-out",
    personId: "p-alex",
    shiftId: "sh-alex-mon",
    type: "out",
    at: `${mon}T08:04:00.000Z`,
    source: "app",
    insideGeofence: true,
  },
];

export const TIME_OFF: TimeOffRequest[] = [
  {
    id: "to-noah",
    personId: "p-noah",
    startDate: addDays(DEMO_TODAY, 10),
    endDate: addDays(DEMO_TODAY, 12),
    kind: "annual",
    hours: 16,
    status: "pending",
    note: "Family in Melbourne",
  },
  {
    id: "to-elise",
    personId: "p-elise",
    startDate: addDays(DEMO_TODAY, 21),
    endDate: addDays(DEMO_TODAY, 21),
    kind: "personal",
    hours: 8,
    status: "approved",
    note: "Specialist appointment",
  },
];

export const AVAILABILITY: AvailabilityWindow[] = [
  { id: "av-alex-1", personId: "p-alex", weekday: 5, start: "09:00", end: "21:00", preferred: true },
  { id: "av-alex-2", personId: "p-alex", weekday: 6, start: "09:00", end: "18:00", preferred: true },
  { id: "av-alex-3", personId: "p-alex", weekday: 0, start: "10:00", end: "16:00", preferred: false },
  { id: "av-alex-4", personId: "p-alex", weekday: 2, start: "12:00", end: "21:00", preferred: true },
  { id: "av-mei-1", personId: "p-mei", weekday: 6, start: "07:00", end: "15:00", preferred: true },
  { id: "av-mei-2", personId: "p-mei", weekday: 0, start: "07:00", end: "15:00", preferred: true },
];

export const NEWS: NewsItem[] = [
  {
    id: "news-1",
    storeId: "st-bondi",
    title: "Saturday late trade — extra closer needed",
    body: "Oxford Street event tonight. If you can stay past 8, grab the open closer in the market. Meal deal on us after 7.",
    authorId: "p-priya",
    publishedAt: `${sat}T01:10:00.000Z`,
    pinned: true,
  },
  {
    id: "news-2",
    storeId: "all",
    title: "UKG is gone. This is ClickIt.",
    body: "Rosters, offers, clocks and approvals live here now. Your old UKG login will not work after tonight. If something looks off, ping Riley — do not text your area manager a screenshot of a 1998 timesheet.",
    authorId: "p-riley",
    publishedAt: `${wed}T22:00:00.000Z`,
    pinned: true,
  },
  {
    id: "news-3",
    storeId: "st-bondi",
    title: "Fresh reset Monday 5:30am",
    body: "New seasonal planogram. Jordan has the run sheet. Early crew please do not pull the stonefruit end until the photo lands.",
    authorId: "p-jordan",
    publishedAt: `${fri}T08:30:00.000Z`,
    pinned: false,
  },
];

export const TASKS: FloorTask[] = [
  {
    id: "tk-1",
    storeId: "st-bondi",
    departmentId: "checkout",
    title: "Count $50 notes in till 3 before lunch",
    dueDate: sat,
    assignedToId: "p-alex",
    status: "open",
    createdById: "p-casey",
  },
  {
    id: "tk-2",
    storeId: "st-bondi",
    departmentId: "fresh",
    title: "Cull berries and photo the wet rack",
    dueDate: sat,
    assignedToId: "p-luca",
    status: "open",
    createdById: "p-jordan",
  },
  {
    id: "tk-3",
    storeId: "st-bondi",
    title: "Fire warden walk — exits 2 and 4",
    dueDate: sat,
    assignedToId: "p-priya",
    status: "done",
    createdById: "p-priya",
  },
  {
    id: "tk-4",
    storeId: "st-bondi",
    departmentId: "online",
    title: "Stage 40 click & collect totes by 11",
    dueDate: sat,
    assignedToId: "p-noah",
    status: "open",
    createdById: "p-priya",
  },
];

export const INTEGRATIONS: Integration[] = [
  {
    id: "int-ukg",
    name: "UKG Pro WFM",
    vendor: "UKG",
    category: "wfm",
    status: "connected",
    lastSyncAt: `${fri}T20:15:00.000Z`,
    description:
      "One-way import of historical punches, employee numbers and residual schedules so you can leave UKG without losing a fortnight.",
    objects: ["Employees", "Schedules", "Punches", "Pay codes"],
    direction: "import",
  },
  {
    id: "int-xero",
    name: "Xero Payroll",
    vendor: "Xero",
    category: "payroll",
    status: "connected",
    lastSyncAt: `${thu}T18:02:00.000Z`,
    description: "Award-split hours export. Ordinary, Saturday, Sunday, evening — already coded.",
    objects: ["Timesheets", "Leave balances", "Pay items"],
    direction: "export",
  },
  {
    id: "int-myob",
    name: "MYOB Business",
    vendor: "MYOB",
    category: "payroll",
    status: "available",
    description: "Alternative AU payroll export if the books sit in MYOB.",
    objects: ["Timesheets", "Employees"],
    direction: "export",
  },
  {
    id: "int-entra",
    name: "Microsoft Entra ID",
    vendor: "Microsoft",
    category: "identity",
    status: "connected",
    lastSyncAt: `${sat}T00:10:00.000Z`,
    description: "SSO for salaried and office roles. Floor staff can keep phone + store PIN.",
    objects: ["Users", "Groups", "SSO"],
    direction: "import",
  },
  {
    id: "int-google",
    name: "Google Calendar",
    vendor: "Google",
    category: "calendar",
    status: "connected",
    lastSyncAt: `${sat}T00:40:00.000Z`,
    description: "Published shifts land on personal calendars. Drafts stay in ClickIt.",
    objects: ["Events"],
    direction: "export",
  },
  {
    id: "int-outlook",
    name: "Outlook Calendar",
    vendor: "Microsoft",
    category: "calendar",
    status: "available",
    description: "Same as Google, for anyone still living in Outlook.",
    objects: ["Events"],
    direction: "export",
  },
  {
    id: "int-slack",
    name: "Slack",
    vendor: "Slack",
    category: "comms",
    status: "connected",
    lastSyncAt: `${fri}T21:00:00.000Z`,
    description: "Open-shift pings to #bondi-floor. No more ‘can anyone do Sunday’ in a 80-person chat.",
    objects: ["Channels", "Notifications"],
    direction: "export",
  },
  {
    id: "int-teams",
    name: "Microsoft Teams",
    vendor: "Microsoft",
    category: "comms",
    status: "available",
    description: "Store channel notifications for published rosters and approved leave.",
    objects: ["Channels", "Notifications"],
    direction: "export",
  },
  {
    id: "int-pos",
    name: "Store timeclock / POS",
    vendor: "Northside POS",
    category: "pos",
    status: "syncing",
    lastSyncAt: `${sat}T02:12:00.000Z`,
    description: "Kiosk punches at the service desk. Geofence + employee number, not a Kronos brick.",
    objects: ["Punches", "Tills"],
    direction: "bidirectional",
  },
  {
    id: "int-fairwork",
    name: "Fair Work award engine",
    vendor: "ClickIt",
    category: "award",
    status: "connected",
    lastSyncAt: `${sat}T00:00:00.000Z`,
    description: "General Retail Industry Award splits baked into every shift. No more guessing Sunday.",
    objects: ["GRIA", "Penalty rates", "Breaks"],
    direction: "bidirectional",
  },
];

export const SYNC_EVENTS: SyncEvent[] = [
  {
    id: "se-1",
    integrationId: "int-ukg",
    at: `${fri}T20:15:00.000Z`,
    message: "Imported 1,204 historical punches and 186 residual UKG shifts for NF-104.",
    level: "ok",
  },
  {
    id: "se-2",
    integrationId: "int-ukg",
    at: `${fri}T20:16:00.000Z`,
    message: "3 UKG pay codes had no GRIA mapping and were parked for Riley.",
    level: "warn",
  },
  {
    id: "se-3",
    integrationId: "int-pos",
    at: `${sat}T02:12:00.000Z`,
    message: "Kiosk 2 retrying — last heartbeat 4 minutes late.",
    level: "warn",
  },
  {
    id: "se-4",
    integrationId: "int-xero",
    at: `${thu}T18:02:00.000Z`,
    message: "Fortnight export posted. 42 timesheets, 0 rejected.",
    level: "ok",
  },
];

export function createInitialState(): AppState {
  return {
    people: PEOPLE,
    stores: STORES,
    shifts: SHIFTS,
    offers: OFFERS,
    punches: PUNCHES,
    timeOff: TIME_OFF,
    availability: AVAILABILITY,
    news: NEWS,
    tasks: TASKS,
    integrations: INTEGRATIONS,
    syncEvents: SYNC_EVENTS,
    currentUserId: "p-alex",
    actingStoreId: "st-bondi",
  };
}
